---
- name: Install web server - play 1st 
  hosts: dev 
  vars:
    - apache_pkg_name: httpd
    - firewall_pkg_name: firewalld 
    - apache_svc_name: httpd 
    - firewall_svc_name: firewalld 
    - fire_rule: http 
    - apache_documentroot: "/var/www/html"
  tasks:
    - name: INstall {{ apache_pkg_name }} package - task-01
      ansible.builtin.yum:
         name: "{{ apache_pkg_name }}" 
         state: present 

    - name: Start and enable {{ apache_svc_name }} - task-02
      ansible.builtin.service:
         name: "{{ apache_svc_name }}"
         state: started 
         enabled: true 

    - name: Deploy application - index.html - task-03 
      ansible.builtin.copy: 
         src: index.html 
         dest: "{{apache_documentroot}}/index.html"

    - name: Install firewalld package - {{ firewall_pkg_name }} - task-04
      ansible.builtin.yum:
         name: "{{ firewall_pkg_name }}" 
         state: present 

    - name: Start and enable {{ firewall_svc_name }} - task-05
      ansible.builtin.service:
         name: "{{ firewall_svc_name }}"
         state: started 
         enabled: true 


    - name: Adding firewall rule - {{fire_rule}} - task -06 
      ansible.posix.firewalld:
          service: "{{ fire_rule }}"
          immediate: yes
          permanent: yes
          state: enabled
...
