---
- name: Register example.
  hosts: dev
  tasks:
    - name: Check status.
      ansible.builtin.shell: systemctl status sshd 
      register: sshd_outcome 

    - name: Print/display 
      ansible.builtin.debug:
         var: sshd_outcome

    - name: Print/display-02
      ansible.builtin.debug:
         msg: "This is the value - {{sshd_outcome.rc}} , start time {{sshd_outcome.start}}"

    
