---
- name: Patch server
  hosts: servera.lab.example.com 
  tasks:
    - name: Install patch 
      ansible.builtin.yum:
          name: "@Server with GUI"
          state: latest 
      notify:
         - reboot

  handlers:
    - name: reboot 
      ansible.builtin.reboot:
        reboot_timeout: 50

      
