---
- name: User & Group mgmt 
  hosts: dev
  tasks:
    - name: Group Create 
      ansible.builtin.group: 
         name: app01_grp 
         gid: 98765

    - name: User Create 
      ansible.builtin.user:
         name: user111
         group: app01_grp
         uid: 7654
         comment: "Test User"
         shell: /bin/bash 
         password: "{{ 'redhat' | password_hash('sha512') }}"
...
