---
- name: User add 
  hosts: all
  tasks:
    - name: User addition - task-01 
      ansible.builtin.user:
         name: user110
         state: present 
         password: "{{ 'redhat' | password_hash('sha512') }}"
         uid: 54321
