---
- name: Installing custom facts 
  hosts: all 
  vars:
     facts_file: "custom.fact" 
     facts_location: /etc/ansible/facts.d
  tasks:
    - name: Create the remote directory
      ansible.builtin.file:
         path: "{{ facts_location }}"
         state: directory
         recurse: yes

    - name: Install facts 
      ansible.builtin.copy:
         src: "{{ facts_file }}"
         dest: "{{ facts_location }}"
