---
- name: Recurring cron job
  hosts: webservers
  become: true
  vars:
    default_target: "graphical.target"
  tasks:
   - name: Crontab file exists
     ansible.builtin.cron:
        name: Add date and time to a file
        job: date >> /home/devops/my_date_time_cron_job
        minute: "*/2"
        hour: 9-16
        weekday: 1-5
        user: devops
        cron_file: add-date-time
        state: present

   - name: Get current boot target
     ansible.builtin.command:
         cmd: systemctl get-default
     changed_when: false
     register: target

   - name: Display 
     ansible.builtin.debug:
        var: target

   - name: Set default boot target
     ansible.builtin.command:
        cmd: systemctl set-default {{ default_target }}
      #when: default_target not in target['stdout']
     when: default_target not in target.stdout

