---
- name: Apache deployment and config change.
  hosts: all
  vars: 
     - package_list:
          - httpd
          - firewalld 
     - service_list:
          - httpd
          - firewalld 
     - check_path: /var/www/html/{{inventory_hostname}}
  tasks:
     - name: Install required packages.
       ansible.builtin.yum:
           name: "{{ package_list }}"
           state: present 
     
     - name: Start and enable required service.
       ansible.builtin.service:
           name: "{{ item }}"
           state: started 
           enabled: true 
       loop: "{{ service_list }}"

     - name: Apache config changes.
       ansible.builtin.template:
           src: myhttpd-config-change-conf.j2
           dest: /etc/httpd/conf.d/myhttpd.conf 
       notify:
          - apache service restart 

     - name: Check the dir
       ansible.builtin.stat:
          path: "{{ check_path }}"
       register: check_path_output
           
     - name: Check and Create dir.
       ansible.builtin.file:
          path: "{{ check_path }}"
          state: directory
       when: check_path_output.stat.exists == false 

     - name: Application deployment - index.html 
       ansible.builtin.copy:
          content: "This is my web server - {{ inventory_hostname }}\n" 
          dest: /var/www/html/{{inventory_hostname}}/index.html 

     - name: Adding firewall rule - http
       ansible.posix.firewalld:
          service: "{{ item }}"
          immediate: yes 
          permanent: yes
          state: enabled
       loop:
           - http
           - https

  handlers:
     - name: apache service restart
       ansible.builtin.service:
           name: httpd 
           state: restarted 
...
