---
- name: file example 
  hosts: dev
  tasks:
    - name: Creating dir if not present.
      ansible.builtin.file:
          path: /var/www/apache
          state: directory
          mode: '0755'
          setype: httpd_sys_content_t

