---
- name: Check file/dir 
  hosts: test 
  vars:
     check_path: "/var/www/html/serverd/"
  tasks:
     - name: Check the dir 
       ansible.builtin.stat: 
          path: "{{ check_path }}"
       register: check_path_output 

     - name: Display all output
       ansible.builtin.debug:
          var: check_path_output

     - name: Check and Create dir.
       ansible.builtin.file:
          path: "{{ check_path }}"
          state: directory 
       when: check_path_output.stat.exists == false
