---
- name: DIsplay 
  hosts: dev 
  tasks:
    - name: Check condition - data 
      #ansible.builtin.shell: cat /etc/passwd | grep -w ^root1
      ansible.builtin.shell: cat /etc/passwd | grep -w ^root
      register: output 
      ignore_errors: yes

    - name: Display 
      ansible.builtin.debug:
        var: output

    - name: Check outcome-01
      ansible.builtin.debug:
        msg: "User present"
      when: output.rc == 0

    - name: Check outcome-02 
      ansible.builtin.debug:
        msg: "User absent"
      when: output.rc != 0
