---
- name: Dict example for loop
  hosts: all 
  tasks:
    - name: Group creation.
      ansible.builtin.group:
          name: "{{ item }}"
          state: present
      when: inventory_hostname in groups['dev']
      loop:
          - unixadm_grp1
          - dbadm_grp1
          - middleware_grp1 
          - app10_grp1

    - name: User Creation.
      ansible.builtin.user:
          name: "{{ item.name }}"
          state: present 
          group: "{{ item.grp }}"
          uid: "{{ item.uid_no }}"
      when: inventory_hostname in groups['dev']
      loop:
          - {name: user11 , grp: unixadm_grp1, uid_no: 33211}
          - {name: user21 , grp: dbadm_grp1, uid_no: 33212}
          - {name: user31 , grp: middleware_grp1, uid_no: 33213}
          - {name: user41 , grp: app10_grp1, uid_no: 33214}
          - name: user51 
            grp: app10_grp1 
            uid_no: 33215}

    - name: Display - task-03 
      ansible.builtin.debug:
          msg: "Task-03" 
