---
- name: Dict example for loop
  hosts: all 
  tasks:
    - name: Group creation.
      ansible.builtin.group:
          name: "{{ item }}"
          state: present
      loop:
          - unixadm_grp
          - dbadm_grp
          - middleware_grp 
          - app10_grp 

    - name: User Creation.
      ansible.builtin.user:
          name: "{{ item.name }}"
          state: present 
          group: "{{ item.grp }}"
          uid: "{{ item.uid_no }}"
      loop:
          - {name: user1 , grp: unixadm_grp, uid_no: 33221}
          - {name: user2 , grp: dbadm_grp, uid_no: 33222}
          - {name: user3 , grp: middleware_grp, uid_no: 33223}
          - {name: user4 , grp: app10_grp, uid_no: 33224}
