---
- name: Handlers example 
  hosts: dev
  tasks:
    - name: DIsplay task-01
      ansible.builtin.debug:
          msg: "Task-01 - done Apache config change" 
      changed_when: true 
      notify:
        - restart apache service 

    - name: DIsplay task-02
      ansible.builtin.debug:
          msg: "Task-02 - done" 
      changed_when: true 


    - name: DIsplay task-03
      ansible.builtin.debug:
          msg: "Task-03 - done" 
  handlers:
     - name: restart apache service
       ansible.builtin.service:
          name: httpd
          state: restarted 
