---
- name: COndition Test 
  hosts: all 
  tasks:
     - name: Create user
       ansible.builtin.user:
          user: user-cisco-01 
          state: present 
       register: user_output 

     - name: validation 
       ansible.builtin.debug:
          var: user_output

     - name: Validation - outcome 
       ansible.builtin.debug:
          msg: "Value is - {{ user_output.state }} "
       when: 
          - user_output.state == "present" 
          #- ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Fedora"
          - ansible_facts.distribution == "RedHat" or ansible_facts.distribution == "Fedora"

     - name: DIsplay value 
       ansible.builtin.debug:
           msg: "Value of distribution = {{ ansible_facts['distribution'] }}" 
     
