---
- name: Restart multiple services.
  hosts: all 
  tasks:
    - name: Restart all below services.
      ansible.builtin.service:
          name: "{{ item }}"  
          state: restarted 
      loop: 
          - sshd
          - rsyslog 
          - chronyd 
          - httpd

