---
- name: Discribe the play - my 1st play 
  hosts: test
  tasks:
     - name: Install the latest version of Apache
       ansible.builtin.yum:
         name: httpd
         state: present

     - name: Start and enable apache service.
       ansible.builtin.service:
         name: httpd
         state: started 
         enabled: yes 

     - name: Deploy application - index.html.
       ansible.builtin.copy: 
         content: "This is my web server\n"
         dest: /var/www/html/index.html 

     - name: Install the latest version of firewalld
       ansible.builtin.yum:
         name: firewalld 
         state: present

     - name: Start and enable firewalld service.
       ansible.builtin.service:
         name: firewalld
         state: started 
         enabled: yes 

     - name: Adding http rule.
       ansible.posix.firewalld:
         service: http
         immediate: yes
         permanent: yes
         state: enabled
...

