---
- name: NIC Configuration
  hosts: webservers
  roles:
   - redhat.rhel_system_roles.network
     network_connections:
       - name: eth0
         type: ethernet
         ip:
             route_metric4: 100
             dhcp4: no
             gateway4: 192.0.2.1
             dns:
              - 192.0.2.2
              - 198.51.100.5

             dns_search:
              - example.com
              - subdomain.example.com
             dns_options:
              - rotate
              - timeout:1

             route_metric6: -1
             auto6: no
             gateway6: 2001:db8::1

             address:
                - 192.0.2.3/24
                - 198.51.100.3/26
                - 2001:db8::80/7
